{
 "title": "Barchart per state",
 "time": { "from": "2020-11-18T11:38:52.415Z", "to": "2020-11-20T11:38:52.415Z" },
 "templating": {
  "list": [
   {
    "name": "MaxLK1",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Schleswig-Holstein' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK2",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Hamburg' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK3",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Niedersachsen' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK4",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Bremen' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK5",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Nordrhein-Westfalen' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK6",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Hessen' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK7",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Rheinland-Pfalz' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK8",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Baden-Wuerttemberg' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK9",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Bayern' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK10",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Saarland' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK11",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Berlin' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK12",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Brandenburg' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK13",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Mecklenburg-Vorpommern' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK14",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Sachsen' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK15",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Sachsen-Anhalt' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   },
   {
    "name": "MaxLK16",
    "query": "SELECT \"Landkreis\" FROM (SELECT max(\"Gesamtzahl Fälle\") , \"MaximumAlles\".\"Landkreis\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreis\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Thueringen' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreis\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Meist betroffene Region (nach Infektionen) in Hamburg: $MaxLK2",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Hamburg' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Sachsen: $MaxLK14",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Sachsen' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Saarland: $MaxLK10",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Saarland' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Schleswig-Holstein: $MaxLK1",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Schleswig-Holstein' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Mecklenburg-Vorpommern: $MaxLK13",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Gesamtzahl Infektionen\", \"Gesamtzahl Genesene\", \"Gesamtzahl Todesfälle\" FROM (SELECT max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \"MaximumAlles\".\"Landkreise\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreise\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Mecklenburg-Vorpommern' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Niedersachsen: $MaxLK3",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Niedersachsen' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Rheinland-Pfalz: $MaxLK7",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Rheinland-Pfalz' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Baden-Württemberg: $MaxLK8",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Baden-Wuerttemberg' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Bremen: $MaxLK4",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Bremen' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffener Region (nach Infektionen) in Sachsen-Anhalt: $MaxLK15",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Sachsen-Anhalt' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Bayern: $MaxLK9",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Bayern' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Nordrhein-Westfalen: $MaxLK5",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Nordrhein-Westfalen' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Berlin: $MaxLK11",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Berlin' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Thüringen: $MaxLK16",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Gesamtzahl Infektionen\", \"Gesamtzahl Genesene\", \"Gesamtzahl Todesfälle\" FROM (SELECT max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \"MaximumAlles\".\"Landkreise\" FROM (SELECT \"Counties\".\"name\" AS \"Landkreise\", sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" FROM \"Counties\" INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" WHERE \"state\" = 'Thueringen' GROUP BY \"Counties\".\"name\" ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\nGROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Hessen: $MaxLK6",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Hessen' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Meist betroffene Region (nach Infektionen) in Brandenburg: $MaxLK12",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"Gesamtzahl Infektionen\", \n  \"Gesamtzahl Genesene\", \n  \"Gesamtzahl Todesfälle\" \nFROM \n  (SELECT \n    max(\"Gesamtzahl Fälle\") AS \"Gesamtzahl Infektionen\", \n    max(\"Gesamtzahl Genesene\") AS \"Gesamtzahl Genesene\", \n    max(\"Gesamtzahl Todesfälle\") AS \"Gesamtzahl Todesfälle\", \n    \"MaximumAlles\".\"Landkreise\" \n  FROM \n    (SELECT \"Counties\".\"name\" AS \"Landkreise\", \n    sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n    sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n    sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\" \n      FROM \"Counties\" \n      INNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\" \n      WHERE \"state\" = 'Brandenburg' \n      GROUP BY \"Counties\".\"name\" \n      ORDER BY sum(\"Cases\".\"cases\")) AS \"MaximumAlles\"\n      GROUP BY \"MaximumAlles\".\"Landkreise\"\nORDER BY max(\"Gesamtzahl Fälle\") DESC) AS \"MaximumLandkreis\" \nLIMIT 1\n"
    }
   ]
  }
 ]
}