{
 "title": "Linediagram per state (infections)",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Infektionen in  Sachsen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Infektionen in  Schleswig-Holstein",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Schleswig-Holstein')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Infektionen in  Rheinland-Pfalz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Rheinland-Pfalz')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Infektionen in Hessen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hessen')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Infektionen in Niedersachsen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Niedersachsen')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Infektionen in  Sachsen-Anhalt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen-Anhalt')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Infektionen in Thüringen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Thueringen')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Infektionen in  Bremen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bremen')\r\nGROUP BY 1\r\nORDER BY 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Infektionen in  Hamburg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hamburg')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Infektionen in Mecklenburg-Vorpommern",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Mecklenburg-Vorpommern')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Infektionen in Nordrhein-Westfalen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Nordrhein-Westfalen')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Infektionen in Saarland",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Saarland')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Infektionen in Baden-Württemberg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\nFROM   \"Cases\" \nWHERE\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Baden-Wuerttemberg')\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Infektionen in Brandenburg ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Brandenburg')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Infektionen in Berlin",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Berlin')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Infektionen in Bayern",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"cases\") AS \"Infektionen pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bayern')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  }
 ]
}