{
 "title": "Linediagram per state (deaths)",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Todesfälle in Schleswig-Holstein",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Schleswig-Holstein')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Sachsen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Niedersachsen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Niedersachsen')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Rheinland-Pfalz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Rheinland-Pfalz')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Bremen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bremen')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Hessen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hessen')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Berlin",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "\nSELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\nFROM   \"Cases\" \nWHERE\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Berlin')\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Todesfälle in Bayern",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bayern')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Brandenburg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\nFROM   \"Cases\" \nWHERE\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Brandenburg')\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Todesfälle in Hamburg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hamburg')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Baden-Württemberg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\nFROM   \"Cases\" \nWHERE\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Baden-Wuerttemberg')\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Todesfälle in Mecklenburg-Vorpommern",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Mecklenburg-Vorpommern')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Todesfälle in Nordrhein-Westfalen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Nordrhein-Westfalen')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Saarland",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Saarland')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Todesfälle in Sachsen-Anhalt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \r\n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\r\nFROM   \"Cases\" \r\nWHERE\r\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen-Anhalt')\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Todesfälle in Thüringen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "Personen" }
   ],
   "targets": [
    {
     "rawSql": "\nSELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"dead\") AS \"Gemeldete Todesfälle pro Tag\"\nFROM   \"Cases\" \nWHERE\n\"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Thueringen')\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  }
 ]
}