{
 "title": "Piechart per state (recovered)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Genesene pro 100.000 Einwohner in Berlin",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Berlin'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Brandenburg",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Brandenburg'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Bayern",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Bayern'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Hessen",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Hessen'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Mecklenburg-Vorpommern",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Mecklenburg-Vorpommern'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Niedersachsen",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Niedersachsen'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Nordrhein-Westfalen",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Nordrhein-Westfalen'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Rheinland-Pfalz",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Rheinland-Pfalz'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Baden-Württemberg",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Baden-Wuerttemberg'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Saarland",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Saarland'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Sachsen",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Sachsen'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Sachsen-Anhalt",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Sachsen-Anhalt'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Schleswig-Holstein",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Schleswig-Holstein'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Thüringen",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Thueringen'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Bremen",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Bremen'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in Hamburg",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (\"sumCases\"*100000)/\"Einwohner\", \"name\", now() as time FROM\r\n(SELECT \r\ndistinct \"Counties\".\"name\" AS \"name\", sum(\"recovered\") AS \"sumCases\", \"population\" AS \"Einwohner\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" WHERE \"state\" = 'Hamburg'\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY sum(\"recovered\") DESC) AS \"Cases\"\r\nORDER BY  (\"sumCases\"*100000)/\"Einwohner\" DESC\r\nLIMIT 10"
    }
   ]
  }
 ]
}