{
 "title": "Total Germany (counties/states)",
 "description": "Hier bearbeitet Leni ihre Dashboards",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "summeInfektionen",
    "query": "SELECT sum(\"cases\") AS \"Gesamtsumme der Infektionen\" FROM \"Cases\""
   },
   {
    "name": "summeTodesfaelle",
    "query": "SELECT sum(\"dead\") FROM \"Cases\" "
   },
   {
    "name": "summeGenesen",
    "query": "SELECT sum(\"recovered\") FROM \"Cases\""
   },
   {
    "name": "summeAktiveFaelle",
    "query": "SELECT (sum(\"cases\")-sum(\"recovered\")-sum(\"dead\")) FROM \"Cases\""
   },
   {
    "name": "summeInfektionenVor7Tagen",
    "query": "SELECT sum(\"cases\") FROM \"Cases\" WHERE \"date\" < now() - interval '1 week'"
   },
   {
    "name": "summeTodesfaelleVor7Tagen",
    "query": "SELECT sum(\"dead\") FROM \"Cases\" WHERE \"date\" < now() - interval '1 week'"
   },
   {
    "name": "summeGenesenVor7Tagen",
    "query": "SELECT sum(\"recovered\") FROM \"Cases\" WHERE \"date\" < now() - interval '1 week'"
   },
   {
    "name": "einwohnerBW",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Baden-Württemberg'"
   },
   {
    "name": "einwohnerSH",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Schleswig-Holstein'"
   },
   {
    "name": "einwohnerSN",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Sachsen'"
   },
   {
    "name": "einwohnerSL",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Saarland'"
   },
   {
    "name": "einwohnerBB",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Brandenburg'"
   },
   {
    "name": "einwohnerHE",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Hessen'"
   },
   {
    "name": "einwohnerNW",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Nordrhein-Westfalen'"
   },
   {
    "name": "einwohnerHB",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Bremen'"
   },
   {
    "name": "einwohnerHH",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Hamburg'"
   },
   {
    "name": "einwohnerMV",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Mecklenburg-Vorpommern'"
   },
   {
    "name": "einwohnerBE",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Berlin'"
   },
   {
    "name": "einwohnerTH",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Thüringen'"
   },
   {
    "name": "einwohnerRP",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Rheinland-Pfalz'"
   },
   {
    "name": "einwohnerSA",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Sachsen-Anhalt'"
   },
   {
    "name": "einwohnerNI",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Niedersachsen'"
   },
   {
    "name": "einwohnerBY",
    "query": "SELECT sum(\"population\") FROM \"Counties\" WHERE \"state\" = 'Bayern'"
   }
  ]
 },
 "panels": [
  {
   "title": "Infektionen pro 100.000 Einwohner (Bundesländer)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 0 },
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerSH AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Schleswig-Holstein'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Schleswig-Holstein\" UNION \n\n\n\nSELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerHH AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Hamburg'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Hamburg\" UNION \n\n\n\nSELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerBY AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Bayern'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Bayern\" UNION \n  \n\nSELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerBE AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Berlin'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Berlin\" UNION \n\n\n\n  SELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerBB AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Brandenburg'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Brandenburg\" UNION \n\n\n    SELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerHB AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Bremen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Bremen\" UNION \n\n\n\n\n      SELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerHE AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Hessen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Hessen\" UNION \n\n\n\n      SELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerMV AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Mecklenburg-Vorpommern'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Mecklenburg-Vorpommern\" UNION \n\n\n\n        SELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerNI AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Niedersachsen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Niedersachsen\" UNION \n\n\n\n        SELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerNW AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Nordrhein-Westfalen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Nordrhein-Westfalen\" UNION \n\n\n\n          SELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerRP AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Rheinland-Pfalz'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Rheinland-Pfalz\" UNION \n\n\nSELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerSL AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Saarland'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Saarland\" UNION \n\n\nSELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerSN AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Sachsen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Sachsen\" UNION \n\n\nSELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerSA AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Sachsen-Anhalt'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Sachsen-Anhalt\" UNION \n\n\nSELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerBW AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Baden-Wuerttemberg'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Baden-Württemberg\" UNION \n  \n\nSELECT \"Bundesland\", \"Infektionen\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\")*100000/$einwohnerTH AS \"Infektionen\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Thueringen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Thüringen\"\n\n"
    }
   ]
  },
  {
   "title": "Infektionsfälle insgesamt pro Bundesland",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 0 },
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerSH AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Schleswig-Holstein'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Schleswig-Holstein\" UNION \r\n\r\n\r\n\r\nSELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerHH AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Hamburg'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Hamburg\" UNION \r\n\r\n\r\n\r\nSELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerBY AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Bayern'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Bayern\" UNION \r\n  \r\n\r\nSELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerBE AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Berlin'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Berlin\" UNION \r\n\r\n\r\n\r\n  SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerBB AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Brandenburg'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Brandenburg\" UNION \r\n\r\n\r\n    SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerHB AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Bremen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Bremen\" UNION \r\n\r\n\r\n\r\n\r\n      SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerHE AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Hessen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Hessen\" UNION \r\n\r\n\r\n\r\n      SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerMV AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Mecklenburg-Vorpommern'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Mecklenburg-Vorpommern\" UNION \r\n\r\n\r\n\r\n        SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerNI AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Niedersachsen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Niedersachsen\" UNION \r\n\r\n\r\n\r\n        SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerNW AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Nordrhein-Westfalen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Nordrhein-Westfalen\" UNION \r\n\r\n\r\n\r\n          SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerRP AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Rheinland-Pfalz'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Rheinland-Pfalz\" UNION \r\n\r\n\r\nSELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerSL AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Saarland'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Saarland\" UNION \r\n\r\n\r\nSELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerSN AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Sachsen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Sachsen\" UNION \r\n\r\n\r\nSELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"cases\")*100000/$einwohnerSA AS \"Infektionsfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Sachsen-Anhalt'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Sachsen-Anhalt\" UNION \r\n\r\n\r\n\r\nSELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM ( SELECT (SELECT \"name\" FROM \"States\" WHERE \"name\" = 'Thueringen') AS \"Bundesland\", (sum(\"cases\")*100000)/$einwohnerTH AS \"Infektionsfälle\", (SELECT \"lat\" FROM \"States\" WHERE \"name\" = 'Thueringen') AS \"lat\", (SELECT \"long\" FROM \"States\" WHERE \"name\" = 'Thueringen') AS \"long\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \r\nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Thüringen')) AS \"Thüringen\" UNION\r\n\r\n\r\n\r\n SELECT \"Bundesland\", \"Infektionsfälle\", \"lat\", \"long\" FROM ( SELECT (SELECT \"name\" FROM \"States\" WHERE \"name\" = 'Baden-Wuerttemberg') AS \"Bundesland\", (sum(\"cases\")*100000)/$einwohnerBW AS \"Infektionsfälle\", (SELECT \"lat\" FROM \"States\" WHERE \"name\" = 'Baden-Wuerttemberg') AS \"lat\", (SELECT \"long\" FROM \"States\" WHERE \"name\" = 'Baden-Wuerttemberg') AS \"long\"\r\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \r\nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Baden-Württemberg')) AS \"Baden-Württemberg\""
    }
   ]
  },
  {
   "title": "Infektionen pro 100.000 Einwohner (Regionen)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 7, "x": 7, "y": 0 },
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  \"Counties\".\"name\" AS \"Kreis\", \n  (sum(\"Cases\".\"cases\")*100000)/\"population\" AS \"Infektionsfälle\", \n  \"Counties\".\"lat\",\n  \"Counties\".\"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nGROUP BY \n  \"Counties\".\"name\", \"Counties\".\"lat\", \"Counties\".\"long\", \"population\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(\"cases\") AS \"Anzahl der Infektionen\",\n  sum(\"recovered\") AS \"Anzahl der Genesenen\",\n  sum(\"dead\") AS \"Anzahl der Todesfälle\",\n((SELECT sum(\"Cases\".\"cases\"))::decimal/(SELECT sum(\"Cases\".\"cases\") FROM \"Cases\" WHERE  \"date\" < now()-interval'1 week')::decimal) AS \"R-Wert\" \nFROM \"Cases\"\n"
    }
   ]
  },
  {
   "title": "Genesene in ganz Deutschland pro Tag (absolute Werte)",
   "type": "graph",
   "description": "Dieses Diagramm zeigt die genesenen Infektionsfälle pro Tag. Der genesene Fall wird an dem Datum gezählt, an dem die Infektion ursprünglich gemeldet wurde, nicht an dem Datum an dem die Person wieder genesen wurde.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"recovered\") AS \"Infektionsfälle, die später als genesen gemeldet wurden\"\nFROM   \"Cases\" \nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Infektionen in ganz Deutschland pro Tag (absolute Werte)",
   "type": "graph",
   "description": "Dieses Diagramm zeigt die Infektionsfälle, die insgesamt pro Tag in ganz Deutschland gemeldet werden.Tageswerte können von Wochentag zu Wochentag teils stark schwanken, wenn Labore und Gesundheitsämter nicht voll besetzt sind oder geschlossen haben, und darum an einigen Tagen wesentlich weniger Infektionen melden, als tatsächlich auftreten.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"cases\") AS \"Anzahl Infektionen die an diesem Tag gemeldet wurden\"\nFROM   \"Cases\" \nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner (Bundesländer)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 17 },
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerSH AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Schleswig-Holstein'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Schleswig-Holstein\" UNION \r\n\r\n\r\n\r\nSELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerHH AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Hamburg'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Hamburg\" UNION \r\n\r\n\r\n\r\nSELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerBY AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Bayern'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Bayern\" UNION \r\n  \r\n\r\nSELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerBE AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Berlin'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Berlin\" UNION \r\n\r\n\r\n\r\n  SELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerBB AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Brandenburg'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Brandenburg\" UNION \r\n\r\n\r\n    SELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerHB AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Bremen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Bremen\" UNION \r\n\r\n\r\n\r\n\r\n      SELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerHE AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Hessen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Hessen\" UNION \r\n\r\n\r\n\r\n      SELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerMV AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Mecklenburg-Vorpommern'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Mecklenburg-Vorpommern\" UNION \r\n\r\n\r\n\r\n        SELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerNI AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Niedersachsen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Niedersachsen\" UNION \r\n\r\n\r\n\r\n        SELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerNW AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Nordrhein-Westfalen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Nordrhein-Westfalen\" UNION \r\n\r\n\r\n\r\n          SELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerRP AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Rheinland-Pfalz'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Rheinland-Pfalz\" UNION \r\n\r\n\r\nSELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerSL AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Saarland'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Saarland\" UNION \r\n\r\n\r\nSELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerSN AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Sachsen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Sachsen\" UNION \r\n\r\n\r\nSELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerSA AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Sachsen-Anhalt'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Sachsen-Anhalt\" UNION \r\n\r\n\r\nSELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerBW AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Baden-Wuerttemberg'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Baden-Württemberg\" UNION \r\n  \r\n\r\nSELECT \"Bundesland\", \"Genesene\", \"lat\", \"long\" FROM (SELECT\r\n  \"Counties\".\"state\" AS \"Bundesland\", \r\n  sum(\"Cases\".\"recovered\")*100000/$einwohnerTH AS \"Genesene\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\r\nFROM\r\n  \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\r\nWHERE \"state\" = 'Thueringen'\r\nGROUP BY \r\n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Thüringen\"\r\n  \r\n  \r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner (Regionen)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 7, "x": 7, "y": 17 },
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  \"Counties\".\"name\" AS \"Kreis\", \n  (sum(\"Cases\".\"recovered\")*100000)/\"population\" AS \"Genesene\", \n  \"Counties\".\"lat\",\n  \"Counties\".\"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nGROUP BY \n  \"Counties\".\"name\", \"Counties\".\"lat\", \"Counties\".\"long\", \"population\""
    }
   ]
  },
  {
   "title": "Todesfälle in ganz Deutschland pro Tag (absolute Werte)",
   "type": "graph",
   "description": "Dieses Diagramm zeigt die Todesfälle pro Tag. Der Todesfall wird an dem Datum gezählt, an dem die Infektion ursprünglich gemeldet wurde, nicht an dem Datum an dem der Todesfall gemeldet wurde.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"dead\") AS \"Infektionsfälle, die später als Todesfall gemeldet wurden\"\nFROM   \"Cases\" \nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Todesfälle pro 100.000 Einwohner (Bundesländer)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 34 },
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerSH AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Schleswig-Holstein'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Schleswig-Holstein\" UNION \n\n\n\nSELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerHH AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Hamburg'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Hamburg\" UNION \n\n\n\nSELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerBY AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Bayern'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Bayern\" UNION \n  \n\nSELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerBE AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Berlin'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Berlin\" UNION \n\n\n\n  SELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerBB AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Brandenburg'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Brandenburg\" UNION \n\n\n    SELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerHB AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Bremen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Bremen\" UNION \n\n\n\n\n      SELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerHE AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Hessen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Hessen\" UNION \n\n\n\n      SELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerMV AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Mecklenburg-Vorpommern'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Mecklenburg-Vorpommern\" UNION \n\n\n\n        SELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerNI AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Niedersachsen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Niedersachsen\" UNION \n\n\n\n        SELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerNW AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Nordrhein-Westfalen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Nordrhein-Westfalen\" UNION \n\n\n\n          SELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerRP AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Rheinland-Pfalz'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Rheinland-Pfalz\" UNION \n\n\nSELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerSL AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Saarland'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Saarland\" UNION \n\n\nSELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerSN AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Sachsen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Sachsen\" UNION \n\n\nSELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerSA AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Sachsen-Anhalt'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Sachsen-Anhalt\" UNION \n  \n  \nSELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerBW AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Baden-Wuerttemberg'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Baden-Württemberg\" UNION \n  \n  \nSELECT \"Bundesland\", \"Todesfälle\", \"lat\", \"long\" FROM (SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"dead\")*100000/$einwohnerTH AS \"Todesfälle\", \"States\".\"lat\" AS \"lat\", \"States\".\"long\" AS \"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nWHERE \"state\" = 'Thueringen'\nGROUP BY \n  \"Counties\".\"state\", \"States\".\"lat\", \"States\".\"long\") AS \"Thüringen\"\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Todesfälle pro 100.000 Einwohner (Regionen)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 7, "x": 7, "y": 34 },
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  \"Counties\".\"name\" AS \"Kreis\", \n  (sum(\"Cases\".\"dead\")*100000)/\"population\" AS \"Todesfälle\", \n  \"Counties\".\"lat\",\n  \"Counties\".\"long\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nGROUP BY \n  \"Counties\".\"name\", \"Counties\".\"lat\", \"Counties\".\"long\", \"population\""
    }
   ]
  },
  {
   "title": "Werte für ganz Deutschland pro Tag (absolute Werte)",
   "type": "graph",
   "description": "Dieses Diagramm zeigt die Infektionsfälle, die pro Tag gemeldet wurden sowie die Fälle, die davon später als genesenen oder als Todesfall gemeldet wurden.\n- Bewegen Sie die Maus über das Liniendiagramm, um die Werte für jeden Tag zu finden\n- Blenden Sie Linien ein und aus, indem sie unten in der Legende auf die Beschreibung der Linie klicken \n- Halten Sie STRG gedrückt, um auf mehrere Linien gleichzeitigzu klicken\n- Zoomen Sie in einen bestimmten Zeitraum, indem Sie einen Bereich markieren. Dafür müssen Sie die linke Maustaste gedrückt halten und nach links oder rechts ziehen.\n- Machen Sie den Zoom rückgängig, indem Sie STRG+Z gleichzeitig drücken.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"dead\") AS \"Infektionsfälle, die später als Todesfall gemeldet wurden\"\nFROM   \"Cases\" \nGROUP BY 1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"cases\") AS \"Infektionsfälle, die an diesem Tag gemeldet wurden\"\nFROM   \"Cases\" \nGROUP BY 1\nORDER BY 1\n\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Cases\".\"date\",$__interval), \n  sum(\"Cases\".\"recovered\") AS \"Infektionsfälle, die später als genesen gemeldet wurden\"\nFROM   \"Cases\" \nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Datenstand",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 45 },
   "options": {
    "content": "Zuletzt Aktualisiert am  {{lu}}\n\n\nDaten werden seit dem  {{date dl format=\"DD.MM.YYYY\"}} mit einberechnet.\n\n\n\nAlle Daten werden von dem [RKI](https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0) bereitgestellt.\n\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT \"lastUpdate\" AS \"lu\", min(\"date\") AS \"dl\"\nFROM \"Cases\"\nGROUP BY \"lastUpdate\", \"date\" LIMIT 1\n\n"
    }
   ]
  },
  {
   "title": "Übersicht pro Bundesland",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Counties\".\"state\" AS \"Bundesland\", \n  sum(\"Cases\".\"cases\") AS \"Gesamtzahl Fälle\", \n  sum(\"Cases\".\"recovered\") AS \"Gesamtzahl Genesene\", \n  sum(\"Cases\".\"dead\") AS \"Gesamtzahl Todesfälle\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nINNER JOIN \"States\" ON \"Counties\".\"state\" = \"States\".\"name\"\nGROUP BY \n  \"Counties\".\"state\""
    }
   ]
  },
  {
   "title": "Infektionen pro 100.000 Einwohner in ganz Deutschland",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/2903773 AS \"Schleswig-Holstein\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Schleswig-Holstein')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/1847253 AS \"Hamburg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hamburg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/11100394 AS \"Baden-Württemberg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Baden-Wuerttemberg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/13123566 AS \"Bayern\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bayern')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/3644827 AS \"Berlin\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Berlin')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/2521893 AS \"Brandenburg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Brandenburg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/682986 AS \"Bremen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bremen')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/6288080 AS \"Hessen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hessen')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/1610000 AS \"Mecklenburg-Vorpommern\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Mecklenburg-Vorpommern')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/7993608 AS \"Niedersachsen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Niedersachsen')\n\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/17900000 AS \"Nordrhein-Westfalen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Nordrhein-Westfalen')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/4093903 AS \"Rheinland-Pfalz\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Rheinland-Pfalz')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/990509 AS \"Saarland\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Saarland')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/4071971 AS \"Sachsen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/2190000 AS \"Sachsen-Anhalt\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen-Anhalt')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"cases\")*100000)/2137000 AS \"Thüringen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Thueringen')"
    }
   ]
  },
  {
   "title": "Top 10 der meisten Infektionen pro 100.000 Einwohner in einer Region",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \"Counties\".\"name\" AS \"Landkreis\", (sum(\"Cases\".\"cases\")*100000)/\"population\",  now() AS time \r\nFROM \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY (sum(\"Cases\".\"cases\")*100000)/\"population\" DESC  LIMIT 10"
    }
   ]
  },
  {
   "title": "Genesene pro 100.000 Einwohner in ganz Deutschland",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/2903773 AS \"Schleswig-Holstein\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Schleswig-Holstein')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/1847253 AS \"Hamburg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hamburg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/11100394 AS \"Baden-Württemberg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Baden-Wuerttemberg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/13123566 AS \"Bayern\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bayern')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/3644827 AS \"Berlin\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Berlin')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/2521893 AS \"Brandenburg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Brandenburg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/682986 AS \"Bremen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bremen')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/6288080 AS \"Hessen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hessen')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/1610000 AS \"Mecklenburg-Vorpommern\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Mecklenburg-Vorpommern')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/7993608 AS \"Niedersachsen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Niedersachsen')\n\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/17900000 AS \"Nordrhein-Westfalen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Nordrhein-Westfalen')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/4093903 AS \"Rheinland-Pfalz\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Rheinland-Pfalz')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/990509 AS \"Saarland\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Saarland')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/4071971 AS \"Sachsen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/2190000 AS \"Sachsen-Anhalt\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen-Anhalt')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"recovered\")*100000)/2137000 AS \"Thüringen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Thueringen')"
    }
   ]
  },
  {
   "title": "Top 10 der meisten Genesenen pro 100.000 Einwohner in einer Region",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \"Counties\".\"name\" AS \"Landkreis\", (sum(\"Cases\".\"recovered\")*100000)/\"population\",  now() AS time \r\nFROM \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY (sum(\"Cases\".\"recovered\")*100000)/\"population\" DESC  LIMIT 10"
    }
   ]
  },
  {
   "title": "Übersicht pro Region",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Counties\".\"name\" AS \"Landkreis/Stadtkreis\", \n  sum(\"Cases\".\"cases\") AS \"Fälle gesamt\", \n  sum(\"Cases\".\"recovered\") AS \"Genesen gesamt\", \n  sum(\"Cases\".\"dead\") AS \"Todesfälle gesamt\"\nFROM\n  \"Counties\"\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\nGROUP BY \n  \"Counties\".\"name\""
    }
   ]
  },
  {
   "title": "Todesfälle pro 100.000 Einwohner in ganz Deutschland",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 65 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/2903773 AS \"Schleswig-Holstein\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Schleswig-Holstein')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/1847253 AS \"Hamburg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hamburg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/11100394 AS \"Baden-Württemberg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Baden-Wuerttemberg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/13123566 AS \"Bayern\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bayern')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/3644827 AS \"Berlin\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Berlin')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/2521893 AS \"Brandenburg\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Brandenburg')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/682986 AS \"Bremen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Bremen')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/6288080 AS \"Hessen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Hessen')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/1610000 AS \"Mecklenburg-Vorpommern\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Mecklenburg-Vorpommern')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/7993608 AS \"Niedersachsen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Niedersachsen')\n\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/17900000 AS \"Nordrhein-Westfalen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Nordrhein-Westfalen')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/4093903 AS \"Rheinland-Pfalz\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Rheinland-Pfalz')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/990509 AS \"Saarland\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Saarland')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/4071971 AS \"Sachsen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen')"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/2190000 AS \"Sachsen-Anhalt\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Sachsen-Anhalt')\n"
    },
    {
     "rawSql": "SELECT \nnow() AS \"time\", (sum(\"dead\")*100000)/2137000 AS \"Thüringen\"\nFROM \"Cases\" INNER JOIN \"Counties\" ON \"Cases\".\"countyID\" = \"Counties\".\"id\" \nWHERE \"countyID\" IN (SELECT \"id\" FROM \"Counties\" WHERE \"state\" = 'Thueringen')"
    }
   ]
  },
  {
   "title": "Top 10 der meisten Todesfällen pro 100.000 Einwohner in einer Region",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 65 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \"Counties\".\"name\" AS \"Landkreis\", (sum(\"Cases\".\"dead\")*100000)/\"population\",  now() AS time \r\nFROM \"Counties\"\r\nINNER JOIN \"Cases\" ON \"Counties\".\"id\" = \"Cases\".\"countyID\"\r\nGROUP BY \"Counties\".\"name\", \"population\"\r\nORDER BY (sum(\"Cases\".\"dead\")*100000)/\"population\" DESC  LIMIT 10"
    }
   ]
  }
 ]
}